<?php
/**
 * OrderManagementApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * LIO - Order Management API
 *
 * API de gerenciamento de pedidos da LIO.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * OrderManagementApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class OrderManagementApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for orderAddItem
     *
     * .
     *
     */
    public function testOrderAddItem()
    {

    }

    /**
     * Test case for orderCreate
     *
     * .
     *
     */
    public function testOrderCreate()
    {

    }

    /**
     * Test case for orderDelete
     *
     * .
     *
     */
    public function testOrderDelete()
    {

    }

    /**
     * Test case for orderDeleteItem
     *
     * .
     *
     */
    public function testOrderDeleteItem()
    {

    }

    /**
     * Test case for orderGet
     *
     * .
     *
     */
    public function testOrderGet()
    {

    }

    /**
     * Test case for orderGetByParameters
     *
     * .
     *
     */
    public function testOrderGetByParameters()
    {

    }

    /**
     * Test case for orderGetItem
     *
     * .
     *
     */
    public function testOrderGetItem()
    {

    }

    /**
     * Test case for orderGetTransactions
     *
     * .
     *
     */
    public function testOrderGetTransactions()
    {

    }

    /**
     * Test case for orderUpdate
     *
     * .
     *
     */
    public function testOrderUpdate()
    {

    }

    /**
     * Test case for orderUpdateItem
     *
     * .
     *
     */
    public function testOrderUpdateItem()
    {

    }

}
