<?php
/**
 * OrdersItems
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * LIO - Order Management API
 *
 * API de gerenciamento de pedidos da LIO.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;

/**
 * OrdersItems Class Doc Comment
 *
 * @category    Class
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OrdersItems implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'orders_items';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'sku' => 'string',
        'sku_type' => 'string',
        'name' => 'string',
        'description' => 'string',
        'unit_price' => 'int',
        'quantity' => 'int',
        'unit_of_measure' => 'string',
        'details' => 'string',
        'created_at' => '\DateTime',
        'updated_at' => '\DateTime'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerFormats = [
        'sku' => null,
        'sku_type' => null,
        'name' => null,
        'description' => null,
        'unit_price' => null,
        'quantity' => null,
        'unit_of_measure' => null,
        'details' => null,
        'created_at' => 'date-time',
        'updated_at' => 'date-time'
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'sku' => 'sku',
        'sku_type' => 'skuType',
        'name' => 'name',
        'description' => 'description',
        'unit_price' => 'unit_price',
        'quantity' => 'quantity',
        'unit_of_measure' => 'unit_of_measure',
        'details' => 'details',
        'created_at' => 'created_at',
        'updated_at' => 'updated_at'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'sku' => 'setSku',
        'sku_type' => 'setSkuType',
        'name' => 'setName',
        'description' => 'setDescription',
        'unit_price' => 'setUnitPrice',
        'quantity' => 'setQuantity',
        'unit_of_measure' => 'setUnitOfMeasure',
        'details' => 'setDetails',
        'created_at' => 'setCreatedAt',
        'updated_at' => 'setUpdatedAt'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'sku' => 'getSku',
        'sku_type' => 'getSkuType',
        'name' => 'getName',
        'description' => 'getDescription',
        'unit_price' => 'getUnitPrice',
        'quantity' => 'getQuantity',
        'unit_of_measure' => 'getUnitOfMeasure',
        'details' => 'getDetails',
        'created_at' => 'getCreatedAt',
        'updated_at' => 'getUpdatedAt'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    const UNIT_OF_MEASURE_EACH = 'EACH';
    const UNIT_OF_MEASURE_HOURS = 'HOURS';
    const UNIT_OF_MEASURE_DAYS = 'DAYS';
    const UNIT_OF_MEASURE_SECONDS = 'SECONDS';
    const UNIT_OF_MEASURE_CRATE_OF_12 = 'CRATE_OF_12';
    const UNIT_OF_MEASURE_SIX_PACK = 'SIX_PACK';
    const UNIT_OF_MEASURE_GALLON = 'GALLON';
    const UNIT_OF_MEASURE_LITRE = 'LITRE';
    

    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public function getUnitOfMeasureAllowableValues()
    {
        return [
            self::UNIT_OF_MEASURE_EACH,
            self::UNIT_OF_MEASURE_HOURS,
            self::UNIT_OF_MEASURE_DAYS,
            self::UNIT_OF_MEASURE_SECONDS,
            self::UNIT_OF_MEASURE_CRATE_OF_12,
            self::UNIT_OF_MEASURE_SIX_PACK,
            self::UNIT_OF_MEASURE_GALLON,
            self::UNIT_OF_MEASURE_LITRE,
        ];
    }
    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['sku'] = isset($data['sku']) ? $data['sku'] : null;
        $this->container['sku_type'] = isset($data['sku_type']) ? $data['sku_type'] : null;
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['description'] = isset($data['description']) ? $data['description'] : null;
        $this->container['unit_price'] = isset($data['unit_price']) ? $data['unit_price'] : null;
        $this->container['quantity'] = isset($data['quantity']) ? $data['quantity'] : null;
        $this->container['unit_of_measure'] = isset($data['unit_of_measure']) ? $data['unit_of_measure'] : null;
        $this->container['details'] = isset($data['details']) ? $data['details'] : null;
        $this->container['created_at'] = isset($data['created_at']) ? $data['created_at'] : null;
        $this->container['updated_at'] = isset($data['updated_at']) ? $data['updated_at'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        if ($this->container['sku'] === null) {
            $invalid_properties[] = "'sku' can't be null";
        }
        if ($this->container['sku_type'] === null) {
            $invalid_properties[] = "'sku_type' can't be null";
        }
        if ($this->container['unit_price'] === null) {
            $invalid_properties[] = "'unit_price' can't be null";
        }
        if ($this->container['unit_of_measure'] === null) {
            $invalid_properties[] = "'unit_of_measure' can't be null";
        }
        $allowed_values = $this->getUnitOfMeasureAllowableValues();
        if (!in_array($this->container['unit_of_measure'], $allowed_values)) {
            $invalid_properties[] = sprintf(
                "invalid value for 'unit_of_measure', must be one of '%s'",
                implode("', '", $allowed_values)
            );
        }

        if ($this->container['created_at'] === null) {
            $invalid_properties[] = "'created_at' can't be null";
        }
        if ($this->container['updated_at'] === null) {
            $invalid_properties[] = "'updated_at' can't be null";
        }
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        if ($this->container['sku'] === null) {
            return false;
        }
        if ($this->container['sku_type'] === null) {
            return false;
        }
        if ($this->container['unit_price'] === null) {
            return false;
        }
        if ($this->container['unit_of_measure'] === null) {
            return false;
        }
        $allowed_values = $this->getUnitOfMeasureAllowableValues();
        if (!in_array($this->container['unit_of_measure'], $allowed_values)) {
            return false;
        }
        if ($this->container['created_at'] === null) {
            return false;
        }
        if ($this->container['updated_at'] === null) {
            return false;
        }
        return true;
    }


    /**
     * Gets sku
     * @return string
     */
    public function getSku()
    {
        return $this->container['sku'];
    }

    /**
     * Sets sku
     * @param string $sku SKU do produto - identificação única do produto, preferencialmente usando identificações do mercado para o produto, como: <br> - Universal Product Code (UPC),<br> - International Article Number (EAN),<br> - Global Trade Item Number (GTIN),<br> - Australian Product Number (APN),<br> - Outros.<br> Caso seu produto não tenha uma identificação global, utilize informe um ID único proprietário para esse produto.
     * @return $this
     */
    public function setSku($sku)
    {
        $this->container['sku'] = $sku;

        return $this;
    }

    /**
     * Gets sku_type
     * @return string
     */
    public function getSkuType()
    {
        return $this->container['sku_type'];
    }

    /**
     * Sets sku_type
     * @param string $sku_type Tipo de SKU informado, por exemplo:<br> - PTY - para proprietário - ou seja, quando o SKU for sua identificação proprietária.<br> - UPC - Universal Product Code.<br> - EAN - International Article Number.<br> - GTIN - Global Trade Item Number.<br> - APN - Australian Product Number.
     * @return $this
     */
    public function setSkuType($sku_type)
    {
        $this->container['sku_type'] = $sku_type;

        return $this;
    }

    /**
     * Gets name
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     * @param string $name Nome do produto.
     * @return $this
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets description
     * @return string
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     * @param string $description Descrição do produto.
     * @return $this
     */
    public function setDescription($description)
    {
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets unit_price
     * @return int
     */
    public function getUnitPrice()
    {
        return $this->container['unit_price'];
    }

    /**
     * Sets unit_price
     * @param int $unit_price Valor unitário do produto. Exemplo: O valor de R$ 10,00 é representado como 1000.
     * @return $this
     */
    public function setUnitPrice($unit_price)
    {
        $this->container['unit_price'] = $unit_price;

        return $this;
    }

    /**
     * Gets quantity
     * @return int
     */
    public function getQuantity()
    {
        return $this->container['quantity'];
    }

    /**
     * Sets quantity
     * @param int $quantity Quantidade de itens. Caso não seja informado será considerado o valor 1.
     * @return $this
     */
    public function setQuantity($quantity)
    {
        $this->container['quantity'] = $quantity;

        return $this;
    }

    /**
     * Gets unit_of_measure
     * @return string
     */
    public function getUnitOfMeasure()
    {
        return $this->container['unit_of_measure'];
    }

    /**
     * Sets unit_of_measure
     * @param string $unit_of_measure Unidade de medida.
     * @return $this
     */
    public function setUnitOfMeasure($unit_of_measure)
    {
        $allowed_values = $this->getUnitOfMeasureAllowableValues();
        if (!in_array($unit_of_measure, $allowed_values)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'unit_of_measure', must be one of '%s'",
                    implode("', '", $allowed_values)
                )
            );
        }
        $this->container['unit_of_measure'] = $unit_of_measure;

        return $this;
    }

    /**
     * Gets details
     * @return string
     */
    public function getDetails()
    {
        return $this->container['details'];
    }

    /**
     * Sets details
     * @param string $details Detalhes do produto.
     * @return $this
     */
    public function setDetails($details)
    {
        $this->container['details'] = $details;

        return $this;
    }

    /**
     * Gets created_at
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     * @param \DateTime $created_at Data da criação/inclusão do item no pedido. A data deve estar no formato: YYYY-MM-DDThh:mm:ssZ (Exemplo: 20151020T13:13:29.000Z)
     * @return $this
     */
    public function setCreatedAt($created_at)
    {
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets updated_at
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->container['updated_at'];
    }

    /**
     * Sets updated_at
     * @param \DateTime $updated_at Data da última atualização do item no pedido. A data deve estar no formato: YYYY-MM-DDThh:mm:ssZ (Exemplo: 20151020T13:13:29.000Z)
     * @return $this
     */
    public function setUpdatedAt($updated_at)
    {
        $this->container['updated_at'] = $updated_at;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}


